### ISSUE TITLE
Normal Bed Mesh dont appear in Fluidd 

### ISSUE THREAD

**Issue by ManuelPeiro** [kyleisah/Klipper-Adaptive-Meshing-Purging#111] opened 2023-07-11 03:37 UTC
**Describe the issue**
A clear and concise description of what the bug is...

**What slicer are you using?**
Not slicer issue

**Troubleshooting**
I installed Kamp, and it works very well... But I have noticed that since I use it, a few days... If I make a manual Bed Mesh, it does not appear in Fluidd... I found it useful to check wl state of the bed

**Screenshots**

**Klipper log file:**
Please add klipper log file here...

**Sliced Gcode**
Please add sliced gcode file you are using here...

**Additional context**

**Comment by kyleisah** [comment] 2023-07-11 04:23
Can you please share a klipper log file?

**Comment by kyleisah** [comment] 2023-07-12 00:44
I'm going to close this issue. This is likely a client side issue and not a problem that KAMP is causing. All KAMP does is make a mesh. If fluidd or mainsail isn't showing the mesh, then the issue is likely with fluidd or mainsail.

**Closed by kyleisah** 2023-07-12 00:44 UTC

**Comment by ManuelPeiro** [comment] 2023-07-12 05:38
I have see later
